[package]
name = "azalea-bot"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "azalea-bot"
path = "src/main.rs"

[[bin]]
name = "namesniper-bot"
path = "src/bin/namesniper.rs"

[dependencies]
azalea = { git = "https://github.com/azalea-rs/azalea", rev = "6249c295" }
azalea-inventory = { git = "https://github.com/azalea-rs/azalea", rev = "6249c295" }
tokio = { version = "1", features = ["full"] }
eyre = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.8"
reqwest = { version = "0.13", features = ["json", "cookies"] }
parking_lot = "0.12"
regex = "1"

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
lto = true
